version: "3.9"

services:
  school-exam-web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "55011:80"
      - "55012:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=55012
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=password
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
      - DATABASE_URL=postgres://postgres:postgres@postgres-develop:5432/school_exam
    #volumes:
      #- ./conf.d/https/:/https/
    depends_on:
      - postgres
        
  postgres:
    image: postgres
    restart: always
    hostname: "postgres-develop"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_exam
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - school-exam-data:/var/lib/postgresql/data

volumes:
  school-exam-data: