// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolExam.Persistence.DataContext;

#nullable disable

namespace SchoolExam.Persistence.Migrations
{
    [DbContext(typeof(SchoolExamDbContext))]
    [Migration("20220107155940_ChangeBookletSubmissionModel")]
    partial class ChangeBookletSubmissionModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolExam.Domain.Base.FileBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.ToTable("File", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("FileBase");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.CourseAggregate.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2022);

                    b.HasKey("Id");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.CourseAggregate.CourseStudent", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudent", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.CourseAggregate.CourseTeacher", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseTeacher", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GradingTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GradingTableId");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamBooklet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamBooklet", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamBookletPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookletId")
                        .HasColumnType("uuid");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character(32)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("BookletId");

                    b.HasIndex("QrCodeData")
                        .IsUnique();

                    b.ToTable("ExamBookletPage", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamTask", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.GradingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GradingTable", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.StudentLegalGuardian", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LegalGuardianId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentId", "LegalGuardianId");

                    b.HasIndex("LegalGuardianId");

                    b.ToTable("StudentLegalGuardian", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SchoolAggregate.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("School", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SchoolAggregate.SchoolTeacher", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("SchoolId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SchoolTeacher", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AchievedPoints")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ExamTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamTaskId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExamBookletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamBookletId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookletPageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookletPageId")
                        .IsUnique();

                    b.HasIndex("ExamId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionPage", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.BookletPdfFile", b =>
                {
                    b.HasBaseType("SchoolExam.Domain.Base.FileBase");

                    b.Property<Guid>("BookletId")
                        .HasColumnType("uuid");

                    b.HasIndex("BookletId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("BookletPdfFile");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.TaskPdfFile", b =>
                {
                    b.HasBaseType("SchoolExam.Domain.Base.FileBase");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.HasIndex("ExamId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("TaskPdfFile");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.LegalGuardian", b =>
                {
                    b.HasBaseType("SchoolExam.Domain.Entities.PersonAggregate.Person");

                    b.HasDiscriminator().HasValue("LegalGuardian");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.Student", b =>
                {
                    b.HasBaseType("SchoolExam.Domain.Entities.PersonAggregate.Person");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.Teacher", b =>
                {
                    b.HasBaseType("SchoolExam.Domain.Entities.PersonAggregate.Person");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("Teacher_SchoolId");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPagePdfFile", b =>
                {
                    b.HasBaseType("SchoolExam.Domain.Base.FileBase");

                    b.Property<Guid>("SubmissionPageId")
                        .HasColumnType("uuid");

                    b.HasIndex("SubmissionPageId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("SubmissionPagePdfFile");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPdfFile", b =>
                {
                    b.HasBaseType("SchoolExam.Domain.Base.FileBase");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("SubmissionPdfFile");
                });

            modelBuilder.Entity("SchoolExam.Domain.Base.FileBase", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.UserAggregate.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.CourseAggregate.Course", b =>
                {
                    b.OwnsOne("SchoolExam.Domain.ValueObjects.Subject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("Subject");

                            b1.HasKey("CourseId");

                            b1.ToTable("Course");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.CourseAggregate.CourseStudent", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.CourseAggregate.Course", null)
                        .WithMany("_students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.Student", null)
                        .WithMany("_courses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.CourseAggregate.CourseTeacher", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.CourseAggregate.Course", null)
                        .WithMany("_teachers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.Teacher", null)
                        .WithMany("_courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.Exam", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.CourseAggregate.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.Teacher", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.GradingTable", "GradingTable")
                        .WithMany()
                        .HasForeignKey("GradingTableId");

                    b.Navigation("GradingTable");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamBooklet", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.Exam", null)
                        .WithMany("Booklets")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamBookletPage", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.ExamBooklet", null)
                        .WithMany("Pages")
                        .HasForeignKey("BookletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamTask", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.Exam", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ExamId");

                    b.OwnsOne("SchoolExam.Domain.ValueObjects.ExamTaskPosition", "Position", b1 =>
                        {
                            b1.Property<Guid>("ExamTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("ExamTaskId");

                            b1.ToTable("ExamTask");

                            b1.WithOwner()
                                .HasForeignKey("ExamTaskId");

                            b1.OwnsOne("SchoolExam.Domain.ValueObjects.ExamPosition", "End", b2 =>
                                {
                                    b2.Property<Guid>("ExamTaskPositionExamTaskId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Page")
                                        .HasColumnType("integer")
                                        .HasColumnName("EndPage");

                                    b2.Property<double>("Y")
                                        .HasColumnType("double precision")
                                        .HasColumnName("EndY");

                                    b2.HasKey("ExamTaskPositionExamTaskId");

                                    b2.ToTable("ExamTask");

                                    b2.WithOwner()
                                        .HasForeignKey("ExamTaskPositionExamTaskId");
                                });

                            b1.OwnsOne("SchoolExam.Domain.ValueObjects.ExamPosition", "Start", b2 =>
                                {
                                    b2.Property<Guid>("ExamTaskPositionExamTaskId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Page")
                                        .HasColumnType("integer")
                                        .HasColumnName("StartPage");

                                    b2.Property<double>("Y")
                                        .HasColumnType("double precision")
                                        .HasColumnName("StartY");

                                    b2.HasKey("ExamTaskPositionExamTaskId");

                                    b2.ToTable("ExamTask");

                                    b2.WithOwner()
                                        .HasForeignKey("ExamTaskPositionExamTaskId");
                                });

                            b1.Navigation("End")
                                .IsRequired();

                            b1.Navigation("Start")
                                .IsRequired();
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.GradingTable", b =>
                {
                    b.OwnsMany("SchoolExam.Domain.ValueObjects.GradingTableInterval", "Intervals", b1 =>
                        {
                            b1.Property<Guid>("GradingTableId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Grade")
                                .HasColumnType("double precision")
                                .HasColumnName("Grade");

                            b1.HasKey("GradingTableId", "Id");

                            b1.ToTable("GradingTableInterval");

                            b1.WithOwner()
                                .HasForeignKey("GradingTableId");

                            b1.OwnsOne("SchoolExam.Domain.ValueObjects.GradingTableIntervalBound", "End", b2 =>
                                {
                                    b2.Property<Guid>("GradingTableIntervalGradingTableId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("GradingTableIntervalId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Points")
                                        .HasColumnType("integer")
                                        .HasColumnName("EndPoints");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasColumnName("EndType");

                                    b2.HasKey("GradingTableIntervalGradingTableId", "GradingTableIntervalId");

                                    b2.ToTable("GradingTableInterval");

                                    b2.WithOwner()
                                        .HasForeignKey("GradingTableIntervalGradingTableId", "GradingTableIntervalId");
                                });

                            b1.OwnsOne("SchoolExam.Domain.ValueObjects.GradingTableIntervalBound", "Start", b2 =>
                                {
                                    b2.Property<Guid>("GradingTableIntervalGradingTableId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("GradingTableIntervalId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Points")
                                        .HasColumnType("integer")
                                        .HasColumnName("StartPoints");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasColumnName("StartType");

                                    b2.HasKey("GradingTableIntervalGradingTableId", "GradingTableIntervalId");

                                    b2.ToTable("GradingTableInterval");

                                    b2.WithOwner()
                                        .HasForeignKey("GradingTableIntervalGradingTableId", "GradingTableIntervalId");
                                });

                            b1.Navigation("End")
                                .IsRequired();

                            b1.Navigation("Start")
                                .IsRequired();
                        });

                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.Person", b =>
                {
                    b.OwnsOne("SchoolExam.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("StreetName");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("StreetNumber");

                            b1.HasKey("PersonId");

                            b1.ToTable("Person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.StudentLegalGuardian", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.LegalGuardian", null)
                        .WithMany("_children")
                        .HasForeignKey("LegalGuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.Student", null)
                        .WithMany("_legalGuardians")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SchoolAggregate.School", b =>
                {
                    b.OwnsOne("SchoolExam.Domain.ValueObjects.Address", "Location", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("StreetName");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("StreetNumber");

                            b1.HasKey("SchoolId");

                            b1.ToTable("School");

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SchoolAggregate.SchoolTeacher", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.SchoolAggregate.School", null)
                        .WithMany("_teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.Answer", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.ExamTask", null)
                        .WithMany()
                        .HasForeignKey("ExamTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.SubmissionAggregate.Submission", null)
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.Submission", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.ExamBooklet", null)
                        .WithMany()
                        .HasForeignKey("ExamBookletId");

                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPage", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.ExamBookletPage", null)
                        .WithOne("SubmissionPage")
                        .HasForeignKey("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPage", "BookletPageId");

                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolExam.Domain.Entities.SubmissionAggregate.Submission", null)
                        .WithMany("Pages")
                        .HasForeignKey("SubmissionId");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.UserAggregate.User", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.PersonAggregate.Person", null)
                        .WithOne()
                        .HasForeignKey("SchoolExam.Domain.Entities.UserAggregate.User", "PersonId");

                    b.OwnsOne("SchoolExam.Domain.ValueObjects.Role", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Role");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.BookletPdfFile", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.ExamBooklet", null)
                        .WithOne("PdfFile")
                        .HasForeignKey("SchoolExam.Domain.Entities.ExamAggregate.BookletPdfFile", "BookletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.TaskPdfFile", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.ExamAggregate.Exam", null)
                        .WithOne("TaskPdfFile")
                        .HasForeignKey("SchoolExam.Domain.Entities.ExamAggregate.TaskPdfFile", "ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPagePdfFile", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPage", null)
                        .WithOne("PdfFile")
                        .HasForeignKey("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPagePdfFile", "SubmissionPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPdfFile", b =>
                {
                    b.HasOne("SchoolExam.Domain.Entities.SubmissionAggregate.Submission", null)
                        .WithOne("PdfFile")
                        .HasForeignKey("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPdfFile", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.CourseAggregate.Course", b =>
                {
                    b.Navigation("_students");

                    b.Navigation("_teachers");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.Exam", b =>
                {
                    b.Navigation("Booklets");

                    b.Navigation("TaskPdfFile");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamBooklet", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("PdfFile")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.ExamAggregate.ExamBookletPage", b =>
                {
                    b.Navigation("SubmissionPage");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SchoolAggregate.School", b =>
                {
                    b.Navigation("_teachers");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.Submission", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Pages");

                    b.Navigation("PdfFile");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.SubmissionAggregate.SubmissionPage", b =>
                {
                    b.Navigation("PdfFile")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.LegalGuardian", b =>
                {
                    b.Navigation("_children");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.Student", b =>
                {
                    b.Navigation("_courses");

                    b.Navigation("_legalGuardians");
                });

            modelBuilder.Entity("SchoolExam.Domain.Entities.PersonAggregate.Teacher", b =>
                {
                    b.Navigation("_courses");
                });
#pragma warning restore 612, 618
        }
    }
}
